# Generated by Django 4.2.7 on 2025-06-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutorder',
            old_name='email',
            new_name='guest_email',
        ),
    ]
