# Generated by Django 5.2.3 on 2025-06-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_checkoutorder_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutorder',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='billing_city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='billing_postcode',
            field=models.CharField(blank=True, null=True),
        ),
    ]
