# Generated by Django 5.2.3 on 2025-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_rename_address_checkoutorder_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='shipping_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
