# Generated by Django 5.2.3 on 2025-07-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_checkoutorder_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='billing_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
