# Generated by Django 5.2.3 on 2025-08-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_checkoutorder_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='order_session',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
