# Generated by Django 5.2.3 on 2025-08-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_checkoutorder_order_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutorder',
            old_name='guest_email',
            new_name='email',
        ),
    ]
