# Generated by Django 5.2.3 on 2025-06-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
